GET http://localhost:8080/products

###

POST http://localhost:8080/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 100,
    "description": "Description of product 1",
    "image": "product1.jpg"
}

###

GET http://localhost:8080/products/da421f04-edcf-4cbb-8f7e-99779fdfbcbe